version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: ./docker_dir/
    command: sh -c "python3 manage.py migrate --no-input && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./src:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
